### PR TITLE
Ant 32 implement walls

### PR DESCRIPTION
**Pull request by jane0009**
walls and background are implemented using tilemaps

needs ant AI, and needs to implement collisions

### CODE REVIEW

**Review by gsingh2124 — APPROVED** [review]
Great work, might have a solution for collisions soon.

**Comment by maxwell2711** [comment]
I noticed that the pause menu no longer displays when esc is pressed. The map is just obscuring the menu though because I can click around where the buttons should be and return to the main menu.

**Review by Matthew-Lastner — APPROVED** [review]
Looks good from what I can see

**Comment by jane0009** [comment]
perfect! merging

**Pull request merged**
