### PR TITLE
Ant 35 create colony object and initialize colony body

### PR DESCRIPTION
**Pull request by maxwell2711**
Created the colony class, and some basic functions. Also prepared for ants to be integrated.

### CODE REVIEW

**Comment by jane0009** [comment]
this is a good first pass, but i think you should also see if you can get some sort of placeholder sprite to show up that is associated to the Colony object, like for example a body object that prints its name in console when you click on it

**Comment by maxwell2711** [comment]
Ok ill work on that

**Review by gsingh2124 — COMMENTED** [review]
very cool stuff

**Review by jane0009 — APPROVED** [review]
i watched this clusterf*ck happen live in vc. just get it over with

**Review by gsingh2124 — APPROVED** [review]
verry cool stuff 2

**Pull request merged**
